### ISSUE TITLE
Create an executable .exe file for the Project

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Handwritten-Multiple-Digits-Recognizer#3]
Although the project seems complete, it is not readily usable since its usability is restricted to those who can run the project via cmd and have all the bindings installed. Aim of this issue is to resolve by creating a .exe executable of this project as a standalone application which performs the objective of "click and run" right from the user desktop.

Few ideas on how to achieve this?

Maybe look into any python package facilitating the creation of .exe files like "pyinstaller"

**Comment by 0xDeadcell** [comment]
I recommend https://pypi.org/project/auto-py-to-exe/
If you're interested I can convert it for you and make a Pull Request for this.

**Comment by aryashah2k** [comment]
Hi there, thanks for reaching out and showing interest in this project. Yes, please go ahead and help this project get its own .exe file.  You can work on the creation of this exe and create a pull request once done. I will test and merge it. Thanks again!

**Comment by 0xDeadcell** [comment]
Just tried to created a pull request, looks like the file exceeded the size limits of 25MB.
Also when cloning and running your project for the first time I had to manually create the /img/ directory and pip install tensorflow as it was missing from the requirements.txt file.

Is there some other place you'd like me to upload the executable for you? I can also just show you the settings I used for auto-py-to-exe to create it if that's easier.

**Comment by aryashah2k** [comment]
You could possibly upload it on your drive and add the link to download the exe file in the main repo Readme! And in the branch that you created for merging, just make a new folder and add a Readme with a guide on how you went about creating the exe file and add the link there too. That folder will be dedicated to your contribution for my project! @0xDeadcell

**Comment by 0xDeadcell** [comment]
Just sent a pull request for a new directory with the new README.md instructions and google drive link. I am missing a few DLLs required by tensorflow so it may need to be re-built, regardless I left instructions for building it! 👍 :)
# https://github.com/aryashah2k/Handwritten-Multiple-Digits-Recognizer/pull/5

**Comment by aryashah2k** [comment]
Issue shall be re-opened once feasibilty of .exe file is worked out + Code Refactoring is completed.
